### ISSUE TITLE
Quick Survey on Sandstorm BUG: unable to Download CSV.

### ISSUE THREAD

**Issue by Reneeeee** [simonv3/quick-survey#63] opened 2017-07-13 14:32 UTC
Hi,

When hitting the 'Download CSV.' link/tekst under **Results**, nothing happens.

Could this be fixed please?

**Comment by simonv3** [comment] 2017-07-13 16:58
Going to close this as a duplicate of https://github.com/simonv3/quick-survey/issues/53

**Closed as completed by simonv3** 2017-07-13 16:58 UTC
